<!-- Navbar -->
<?php $this->partial("layouts/navbar") ?>

<main>
  <div class="card m-2 shadow-sm">
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h1 class="card-title d-inline-block">Clientes</h1>

        <form class="d-flex p-2" id="formPesquisa2" method="POST">
            <input class="form-control me-2" type="search" id="pesquisa2" placeholder="Nome" aria-label="Search">
            <button class="btn btn-outline-success" id="pesquisar2" type="button">Pesquisar</button>
          </form>
        <div class="text-end d-inline-block m-2">
          <!-- Botão para acionar modal -->
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalCadastro">
            Novo Cliente
          </button>
          <button type="button" onclick="atualizarPagina()" class="btn btn-light shadow-sm">Atualizar</button>
        </div>
      </div>
      <hr>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Nome</th>
            <th scope="col">CPF</th>
            <th scope="col">Telefone</th>
            <th scope="col">Email</th>
            <th scope="col" width="256px" class="text-center">opções</th>
          </tr>
        </thead>
        <tbody>
          <?php if(empty($clientesInfo)) :
            echo '<h1 class="text-center">Nenhum cliente encontrado</h1>';
       		else:
           ?>
          <?php  foreach ($clientesInfo as $info) : ?>    
          <tr>
            <th scope="row"><?php echo $info['id'] ?></th>
            <td><?php echo $info['nome'] ?></td>
            <td><?php echo $info['cpf'] ?></td>
            <td><?php echo $info['telefone'] ?></td>
            <td><?php echo $info['email'] ?></td>
            <td>
              <a href="visualizar.html" type="button" class="btn btn-success">Visualizar</a>
              <button type="button" 
                      class="btn btn-warning" 
                      data-bs-toggle="modal" 
                      data-bs-target="#modalEditar"
                      onclick="editar(this)"
                      >
                    Editar
              </button>
              <a href="painel/excluir/<?php echo $info['id'] ?>" onclick="confirmarExclusao()" class="btn btn-danger">Excluir</a>
            </td>
          </tr>
          <?php endforeach; 
      		endif;
          ?>
        </tbody>
      </table>
    </div>
  </div>
</main>


<!-- Cadastrar Cliente Modal -->
<?php $this->partial("layouts/modalCadastrarCliente") ?>

<!-- Editar Cliente Modal -->
<?php $this->partial("layouts/modalEditarCliente") ?>

<!-- Cadastrar administrador Modal -->
<?php $this->partial("layouts/modalCadastrarAdministrador") ?>

<!-- Arquivos javascript -->
<?php echo \Phalcon\Tag::javascriptInclude("public/js/mascara.js"); ?>

<?php echo \Phalcon\Tag::javascriptInclude("public/js/verificarSenha.js"); ?>

<?php echo \Phalcon\Tag::javascriptInclude("public/js/script.js"); ?>

<?php echo \Phalcon\Tag::javascriptInclude("public/js/dadosForm.js"); ?>
