<div class="modal fade" id="modalSenha" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Alterar senha administrador - <span id="nomeAdm"></span> </h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" id="linkAlt">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Nova senha:</label>
            <input type="password" class="form-control" name="novaSenha" id="senhaAlt">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Confirmar nova senha:</label>
            <input type="password" class="form-control" name="novaSenhaConfirmar" id="confirmarSenhaAlt">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Digite sua senha:</label>
            <input type="password" class="form-control" name="senhaVerificar">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        <button type="button" id="altSenha" class="btn btn-primary">Alterar</button>
      </div>
    </div>
  </div>
</div>