<!-- Modal -->
<div class="modal fade" id="modalCadastro" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cadastrar Cliente</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="painel/cadastrarCliente" id="formCadastrarCliente">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Nome:</label>
            <input type="text" class="form-control" name="nome">
          </div>
          <div class="form-group">
            <label for="" class="col-form-label">CPF</label>
            <input type="text" class="form-control" name="cpf"  maxlength="14" onkeydown="javascript: mascara( this, mascaraCpf );" required>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Telefone</label>
            <input type="text" class="form-control" name="telefone"  maxlength="14" onkeydown="javascript: mascara( this, mascaraTel );" required>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Email</label>
            <input type="text" class="form-control" name="email" required>
          </div>
      </div>
      <div class="modal-footer">
        <div class="square" id="square"></div>
        <div id="options">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button> 
          <input type="submit" id="sub" class="btn btn-primary" value="Cadastrar">
        </div>
      </div>
      </form>
    </div>
  </div>
</div>