<!-- Modal -->
<div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar Cliente - Nome: <span id="nomeCliente"></span> </h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="painel/editarCliente">
            <input type="hidden" id="id" name="id" value="">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Nome:</label>
            <input type="text" class="form-control" id="nome" name="nome">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">CPF</label>
            <input type="text" class="form-control" id="cpf" name="cpf" maxlength="14" onkeydown="javascript: mascara( this, mascaraCpf );">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Telefone</label>
            <input type="text" class="form-control" id="telefone" name="telefone" maxlength="14" onkeydown="javascript: mascara( this, mascaraTel );">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Email</label>
            <input type="text" class="form-control" id="email" name="email">
          </div>
      </div>
      <div class="modal-footer">
        <div class="square" id="square"></div>
        <div id="options">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
          <button type="submit" id="editarCliente" class="btn btn-primary">Editar</button>
        </div>
      </div>
      </form>
    </div>
  </div>
</div>